consumes:
- application/json
definitions:
  mops.GetReportResponse:
    properties:
      report:
        type: string
    type: object
host: localhost:8888
info:
  contact: {}
  title: Metal Operations Server
  version: "1"
paths:
  /report/{name}:
    get:
      description: Renders a report from the named template.
      responses:
        "200":
          description: report response
          schema:
            $ref: '#/definitions/mops.GetReportResponse'
      summary: report template
swagger: "2.0"
